name: Build ZippyARC

on:
  workflow_dispatch:
    inputs:
      build_target:
        description: "Choose which platform to build"
        required: false
        default: "all"
        type: choice
        options:
          - all
          - windows
          - linux

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
      fail-fast: false

    steps:
      - name: Check build target
        if: ${{ github.event.inputs.build_target != 'all' && matrix.os != github.event.inputs.build_target + '-latest' }}
        run: echo "Skipping build for ${{ matrix.os }}" && exit 0

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller customtkinter py7zr screeninfo CTkListbox requests tkinterdnd2

      - name: Build executable
        run: |
          pyinstaller --noconfirm --onefile --windowed --name ZippyARC main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ZippyARC-${{ matrix.os }}
          path: dist/ZippyARC*
